# Generated by Django 4.2 on 2023-05-02 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
