# Generated by Django 4.2 on 2023-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
