# Generated by Django 4.2 on 2023-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='viewCount',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
